from enum import StrEnum


class ErrorCode(StrEnum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    INVALID_REQUEST = "INVALID_REQUEST"
    CAPTCHA_VERIFICATION_FAILED = "CAPTCHA_VERIFICATION_FAILED"
    CAPTCHA_VERIFICATION_UNAVAILABLE = "CAPTCHA_VERIFICATION_UNAVAILABLE"
